// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2frZiFLpJLGaZUb5KWD3y0isKHPTyOao',
    appId: '1:869953916567:web:f7a182782eef581c1d23d2',
    messagingSenderId: '869953916567',
    projectId: 'kirana-billing-app',
    authDomain: 'kirana-billing-app.firebaseapp.com',
    storageBucket: 'kirana-billing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaU_iRrhPhs0drJqZLACyqjm87ZFMQr3Q',
    appId: '1:869953916567:android:0853aafdbb4e03891d23d2',
    messagingSenderId: '869953916567',
    projectId: 'kirana-billing-app',
    storageBucket: 'kirana-billing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rqfOHi8ISIO4Xs5f_qIgN4bsDrF34Ds',
    appId: '1:869953916567:ios:c90dff21a570227b1d23d2',
    messagingSenderId: '869953916567',
    projectId: 'kirana-billing-app',
    storageBucket: 'kirana-billing-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rqfOHi8ISIO4Xs5f_qIgN4bsDrF34Ds',
    appId: '1:869953916567:ios:c90dff21a570227b1d23d2',
    messagingSenderId: '869953916567',
    projectId: 'kirana-billing-app',
    storageBucket: 'kirana-billing-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2frZiFLpJLGaZUb5KWD3y0isKHPTyOao',
    appId: '1:869953916567:web:caf6a5d69d63fa371d23d2',
    messagingSenderId: '869953916567',
    projectId: 'kirana-billing-app',
    authDomain: 'kirana-billing-app.firebaseapp.com',
    storageBucket: 'kirana-billing-app.firebasestorage.app',
  );
}
